### ISSUE TITLE
Passing values to window_1

### ISSUE THREAD

**Issue by max1020** [ffariasdev/alloy-dynamic-navigation-window#2]
Often its need to pass a value from one window to another. This works for me.
1) in the first icon tab i added value="8" to the view and the icon
index.xml:

		<View id="footer">	
            <View class="tabbedBar">
            	<View left="20" class="view-button" controller="window_1" value="8" onClick="Alloy.Globals.app.openController">
	                <Widget class="icon-buttons" icon="icon-fullstar" src="be.k0suke.glyphicon" value="8" />
            </View>
        </View>

2) i modified the openController function in alloy.js and get the value from the index.xml view with data.source.value to pass it like  {nid: dataValue} to window_1
alloy.js:

	   	openController : function(data){ //mod
	   	var c = this;
	   	var data = data; //mod
	   	console.log("data: " + JSON.stringify(data)); //mod
	   	console.log("data.source.value: " + data.source.value); //mod
	   	var dataValue = data.source.value; //mod
		c.setTouchEnabled(false);
		c.setOpacity(0.5);
		setTimeout(function(){
			c.setOpacity(1);
		var controllers = Alloy.createController(c.controller, {nid: dataValue}).getView(); //
		    Alloy.Globals.navigationDefault.openWindow(controllers);
		},200);
	    setTimeout(function(){
	    	c.setTouchEnabled(true);
	    },2000);
	   	
	},

3) finally, access the value from the main index.xml by adding this code in window_1.js

    var args = arguments[0] || {};
    var currentNid = args.nid;
    console.log("nid: " + currentNid);

**Comment by ffariasdev** [comment]
Hello my friend,

Great job!

Thanks for use the code and edit the features. I agree with the modifications, seems to me very useful. Please, commit your modifications for other people too.

Thanks for your job.

**Comment by max1020** [comment]
committed
